'use client';
import {useState} from 'react';
import {nutrients,nutrientText,type NutritionSummary} from '@/lib/nutrition';
import {reviewIngredients,evidenceReviewed,sweetenerContext} from '@/lib/ingredient-evidence';
import type {Product,Constraint} from '@/lib/domain';
export function NutritionPanel({summary,title='Nutrition per serving',targets}:{summary:NutritionSummary;title?:string;targets?:Record<string,number>}){
 const [micro,setMicro]=useState(false);return <section className="nutrition-panel stack"><div className="row between"><h3>{title}</h3><button type="button" className="link" onClick={()=>setMicro(!micro)}>{micro?'Show macros':'Vitamins & minerals'}</button></div><div className="nutrient-grid">{Object.entries(nutrients).filter(([,n])=>n.group===(micro?'micro':'macro')).map(([key,n])=>{const v=summary[key],complete=v?.total>0&&v.known===v.total,target=targets?.[key];return <div className="nutrient-cell" key={key}><span>{n.name}</span><strong>{nutrientText(v,key)}</strong><small>{v?.total?`${v.known}/${v.total} ingredients recorded`:'No ingredients recorded'}</small>{target!=null&&<small>Target: {target} {n.unit}{complete&&target>0?' · '+Math.round(v.value/target*100)+'%':' · comparison incomplete'}</small>}</div>})}</div><p className="fine">“≥” is a partial sum of recorded values, not the complete meal. Unknown values are never counted as zero. Quantities use the selected raw/cooked food state; cooking losses are not modelled.</p></section>
}
export function IngredientReview({product,constraints=[]}:{product:Product;constraints?:Constraint[]}){
 if(!constraints.length)return null;
 const r=reviewIngredients(product,constraints);
 return <section className="stack ingredient-review"><h3>Your household requirements</h3>{r.missing&&<p className="notice">Ingredient information is missing, so exclusions and allergies cannot be checked from this record.</p>}{r.issues.map((i,n)=><p className="notice" key={n}><strong>{i.kind}: {i.value}</strong> · {i.state}. {i.kind==='allergy'?'This is not an allergy-safety assessment.':''}</p>)}{r.unknownExposure&&<p className="fine">{sweetenerContext.text} <a href={sweetenerContext.source} target="_blank" rel="noreferrer">WHO guidance</a></p>}<p className="fine">Requirement checks use recorded names, E numbers and tags. Evidence snapshot {evidenceReviewed}. Personal dislikes stay separate from additive evidence above.</p></section>
}
export function NutritionFields({value,onChange}:{value:Record<string,number>;onChange:(n:Record<string,number>)=>void}){return <details><summary>Nutrition label · macros and micronutrients</summary><p className="fine">Enter amounts per the selected 100 g or 100 ml basis. Leave unknown values blank.</p><div className="formgrid nutrient-inputs">{Object.entries(nutrients).map(([key,n])=><label key={key}>{n.name} ({n.unit})<input type="number" min="0" max="10000000" step="any" value={value[key]??''} onChange={e=>{const next={...value};if(e.target.value==='')delete next[key];else next[key]=Number(e.target.value);onChange(next)}}/></label>)}</div></details>}

export function ProductNutrition({product}:{product:Product}){
 const [micro,setMicro]=useState(false);
 if(!product.basis)return <section className="nutrition-panel stack"><h3>Nutrition information incomplete</h3><p className="muted">The saved source does not specify a compatible per-100-g or per-100-ml basis. Refresh product details or check the package; these values cannot be used to calculate a meal.</p></section>;
 return <section className="nutrition-panel stack"><div className="row between"><h3>Nutrition per {product.basis==='100g'?'100 g':'100 ml'}</h3><button type="button" className="link" onClick={()=>setMicro(!micro)}>{micro?'Show macros':'Vitamins & minerals'}</button></div><div className="nutrient-grid">{Object.entries(nutrients).filter(([,n])=>n.group===(micro?'micro':'macro')).map(([key,n])=>{const value=product.nutrition?.[key],known=typeof value==='number'&&Number.isFinite(value);return <div className="nutrient-cell" key={key}><span>{n.name}</span><strong>{known?nutrientText({value,known:1,total:1},key):'Not recorded'}</strong></div>})}</div><p className="fine">Recorded product values, on the basis above. Missing values and ingredient-based estimates are not treated as measured nutrition. Check the current label.</p></section>
}
