export type AdditiveConcern='low'|'moderate'|'high';
export type AdditiveEvidence={
 id:string;
 name:string;
 codes:string[];
 pattern:RegExp;
 concern:AdditiveConcern;
 summary:string;
 certainty:string;
 source:string;
};
const EFSA='https://www.efsa.europa.eu/en/topics/topic/food-additives';
const IARC_ASP='https://www.iarc.who.int/news-events/aspartame-hazard-and-risk-assessment-results-released/';
const FSA_COLOURS='https://www.food.gov.uk/safety-hygiene/food-additives';
const ANSES_NITRITE='https://www.anses.fr/en/content/reducing-dietary-exposure-nitrites-and-nitrates';
const WHO_NSS='https://www.who.int/news/item/15-05-2023-who-advises-not-to-use-non-sugar-sweeteners-for-weight-control-in-newly-released-guideline';

function codes(...ids:string[]):string[]{return ids.flatMap(id=>[id,id.replace(/^e/,'')])}

export const additiveEvidence:AdditiveEvidence[]=[
 {id:'e102',name:'Tartrazine',codes:codes('e102'),pattern:/\btartrazin|\be\s*[-:]?\s*102\b/i,concern:'moderate',summary:'One of the Southampton colours. The UK Food Standards Agency advises that it may have an adverse effect on activity and attention in children. It remains an authorised colour when labelled.',certainty:'Population warning on labels; not a ban',source:FSA_COLOURS},
 {id:'e104',name:'Quinoline yellow',codes:codes('e104'),pattern:/\bquinoline yellow|\bbe\s*[-:]?\s*104\b|\be\s*[-:]?\s*104\b/i,concern:'moderate',summary:'Southampton colour. UK labels may carry the hyperactivity advisory. Authorised in the EU with specified uses.',certainty:'Label advisory, not an individual diagnosis',source:FSA_COLOURS},
 {id:'e110',name:'Sunset yellow FCF',codes:codes('e110'),pattern:/\bsunset yellow|\be\s*[-:]?\s*110\b/i,concern:'moderate',summary:'Southampton colour with the UK hyperactivity advisory on some products. Still authorised when the name or E number is declared.',certainty:'Label advisory',source:FSA_COLOURS},
 {id:'e122',name:'Azorubine / carmoisine',codes:codes('e122'),pattern:/\bazorubin|\bcarmoisin|\be\s*[-:]?\s*122\b/i,concern:'moderate',summary:'Southampton colour. UK FSA hyperactivity advisory may appear on the label.',certainty:'Label advisory',source:FSA_COLOURS},
 {id:'e124',name:'Ponceau 4R',codes:codes('e124'),pattern:/\bponceau|\be\s*[-:]?\s*124\b/i,concern:'moderate',summary:'Southampton colour with the UK hyperactivity advisory. Authorised with maximum levels.',certainty:'Label advisory',source:FSA_COLOURS},
 {id:'e129',name:'Allura red AC',codes:codes('e129'),pattern:/\ballura red|\be\s*[-:]?\s*129\b/i,concern:'moderate',summary:'Southampton colour. UK labels may warn that it may affect children’s activity and attention.',certainty:'Label advisory',source:FSA_COLOURS},
 {id:'e150c',name:'Ammonia caramel',codes:codes('e150c'),pattern:/\bammonia caramel|\be\s*[-:]?\s*150\s*c\b/i,concern:'high',summary:'Caramel colour produced with ammonia. 4-methylimidazole can form during manufacture. EFSA has assessed it as an authorised colour with specifications; some consumer guides treat ammonia caramel more strictly than plain caramel.',certainty:'Authorised additive; process contaminant is the concern, not a product-specific measurement',source:'https://www.efsa.europa.eu/en/efsajournal/pub/3030'},
 {id:'e150a',name:'Plain caramel',codes:codes('e150a'),pattern:/\bplain caramel|\be\s*[-:]?\s*150\s*a\b/i,concern:'low',summary:'Plain caramel colour. EFSA evaluated caramel colours as authorised when specifications are met. This is not the same process as ammonia caramel (E150c).',certainty:'Authorised colour',source:'https://www.efsa.europa.eu/en/efsajournal/pub/3030'},
 {id:'e150d',name:'Sulphite ammonia caramel',codes:codes('e150d'),pattern:/\bsulphite ammonia caramel|\bsulfite ammonia caramel|\be\s*[-:]?\s*150\s*d\b/i,concern:'moderate',summary:'Caramel colour made with sulphite and ammonia. Same EFSA caramel-colour opinion as E150c, with process contaminants controlled by specifications.',certainty:'Authorised colour with specifications',source:'https://www.efsa.europa.eu/en/efsajournal/pub/3030'},
 {id:'e200',name:'Sorbic acid',codes:codes('e200'),pattern:/\bsorbic acid|\be\s*[-:]?\s*200\b/i,concern:'low',summary:'Preservative re-evaluated by EFSA. Authorised in specified foods. Presence is not an intake calculation.',certainty:'Authorised preservative',source:EFSA},
 {id:'e202',name:'Potassium sorbate',codes:codes('e202'),pattern:/\bpotassium sorbate|\bsorbate de potassium|\be\s*[-:]?\s*202\b/i,concern:'low',summary:'Common sorbate preservative. EFSA considers authorised uses acceptable; some people report sensitivity.',certainty:'Authorised preservative',source:EFSA},
 {id:'e211',name:'Sodium benzoate',codes:codes('e211'),pattern:/\bsodium benzoate|\bbe\s*[-:]?\s*211\b|\be\s*[-:]?\s*211\b/i,concern:'moderate',summary:'Benzoate preservative. Can form benzene with ascorbic acid under some conditions. EFSA has an acceptable daily intake; drinks combining benzoate and vitamin C are the usual discussion point.',certainty:'Authorised; combination chemistry is not measured on the label',source:EFSA},
 {id:'e212',name:'Potassium benzoate',codes:codes('e212'),pattern:/\bpotassium benzoate|\be\s*[-:]?\s*212\b/i,concern:'moderate',summary:'Benzoate preservative, assessed with the benzoate group. Same caveats as sodium benzoate.',certainty:'Authorised preservative',source:EFSA},
 {id:'e220',name:'Sulphur dioxide',codes:codes('e220'),pattern:/\bsulphur dioxide|\bsulfur dioxide|\be\s*[-:]?\s*220\b/i,concern:'moderate',summary:'Sulphite preservative. Must be labelled because it can trigger asthma and is an allergen for sensitive people above 10 mg/kg.',certainty:'Declared allergen class; individual reaction varies',source:'https://www.efsa.europa.eu/en/efsajournal/pub/4438'},
 {id:'e221',name:'Sodium sulphite',codes:codes('e221'),pattern:/\bsodium sulphite|\bsodium sulfite|\be\s*[-:]?\s*221\b/i,concern:'moderate',summary:'Sulphite preservative in the same allergen-labelling class as sulphur dioxide.',certainty:'Declared allergen class',source:'https://www.efsa.europa.eu/en/efsajournal/pub/4438'},
 {id:'e223',name:'Sodium metabisulphite',codes:codes('e223','e224','e225','e226','e227','e228'),pattern:/\bmetabisulphite|\bmetabisulfite|\bsulphite|\bsulfite|\be\s*[-:]?\s*22[3-8]\b/i,concern:'moderate',summary:'Sulphite preservatives. Labels must declare them when above the allergen threshold. Not a general toxicity ranking for every product.',certainty:'Allergen labelling class',source:'https://www.efsa.europa.eu/en/efsajournal/pub/4438'},
 {id:'e249',name:'Potassium nitrite',codes:codes('e249'),pattern:/\bpotassium nitrite|\be\s*[-:]?\s*249\b/i,concern:'high',summary:'Nitrite curing salt. ANSES has advised reducing dietary nitrite/nitrate exposure because of colorectal-cancer associations with processed meat. Still authorised in the EU for specified meat products.',certainty:'Population dietary advice; this product’s dose is not calculated',source:ANSES_NITRITE},
 {id:'e250',name:'Sodium nitrite',codes:codes('e250'),pattern:/\bsodium nitrite|\bnitrite de sodium|\be\s*[-:]?\s*250\b/i,concern:'high',summary:'The common cured-meat nitrite. Linked in epidemiological reviews to colorectal cancer risk from processed meat. Authorised with maximum residual levels; this app does not measure the residue in a pack.',certainty:'Population evidence on processed meat, not a measured dose here',source:ANSES_NITRITE},
 {id:'e251',name:'Sodium nitrate',codes:codes('e251'),pattern:/\bsodium nitrate|\be\s*[-:]?\s*251\b/i,concern:'high',summary:'Nitrate used in curing. Can convert to nitrite. Same ANSES advice to reduce dietary nitrite/nitrate exposure.',certainty:'Population dietary advice',source:ANSES_NITRITE},
 {id:'e252',name:'Potassium nitrate',codes:codes('e252'),pattern:/\bpotassium nitrate|\bsaltpetre|\bsaltpeter|\be\s*[-:]?\s*252\b/i,concern:'high',summary:'Nitrate curing salt. See ANSES guidance on reducing nitrite and nitrate exposure from processed meat.',certainty:'Population dietary advice',source:ANSES_NITRITE},
 {id:'e320',name:'Butylated hydroxyanisole (BHA)',codes:codes('e320'),pattern:/\bbutylated hydroxyanisole|\b\bbha\b|\be\s*[-:]?\s*320\b/i,concern:'high',summary:'Antioxidant. IARC classified BHA as possibly carcinogenic to humans (Group 2B). It remains authorised in the EU with use limits.',certainty:'Hazard classification is not the same as a measured cancer risk from this pack',source:'https://monographs.iarc.who.int/list-of-classifications'},
 {id:'e321',name:'Butylated hydroxytoluene (BHT)',codes:codes('e321'),pattern:/\bbutylated hydroxytoluene|\b\bbht\b|\be\s*[-:]?\s*321\b/i,concern:'high',summary:'Antioxidant related to BHA. Authorised with restrictions. Some consumer assessments treat it as a high-attention additive.',certainty:'Authorised with limits; this pack is not assayed',source:EFSA},
 {id:'e319',name:'Tertiary-butylhydroquinone (TBHQ)',codes:codes('e319'),pattern:/\btbhq|\btertiary-butylhydroquinone|\be\s*[-:]?\s*319\b/i,concern:'high',summary:'Antioxidant used in oils. EFSA has evaluated TBHQ with an ADI. Some jurisdictions restrict uses more tightly than others.',certainty:'Authorised additive with an ADI',source:EFSA},
 {id:'e338',name:'Phosphoric acid',codes:codes('e338'),pattern:/\bphosphoric acid|\be\s*[-:]?\s*338\b/i,concern:'moderate',summary:'Acid in cola-type drinks. EFSA assesses phosphates as a group; high phosphate intake is a concern for people with kidney disease. The label does not show total phosphate from the diet.',certainty:'Group ADI; medical kidney advice is individual',source:'https://www.efsa.europa.eu/en/efsajournal/pub/7468'},
 {id:'e339',name:'Sodium phosphates',codes:codes('e339','e340','e341','e343','e450','e451','e452'),pattern:/\bphosphate|\be\s*[-:]?\s*339\b|\be\s*[-:]?\s*340\b|\be\s*[-:]?\s*341\b|\be\s*[-:]?\s*343\b|\be\s*[-:]?\s*450\b|\be\s*[-:]?\s*451\b|\be\s*[-:]?\s*452\b/i,concern:'moderate',summary:'Added phosphates. EFSA’s group ADI can be approached by processed-food diets. Not the same as naturally occurring phosphorus in foods.',certainty:'Group exposure estimate, not this pack’s milligrams',source:'https://www.efsa.europa.eu/en/efsajournal/pub/7468'},
 {id:'e407',name:'Carrageenan',codes:codes('e407'),pattern:/\bcarrageenan|\bcarragheen|\be\s*[-:]?\s*407(?!a)\b/i,concern:'moderate',summary:'Seaweed-derived thickener. EFSA authorised refined carrageenan. Degraded carrageenan is a different substance. GI-inflammation debates continue in the literature.',certainty:'Authorised as E407; food-grade vs degraded forms are not distinguished on most labels',source:'https://www.efsa.europa.eu/en/efsajournal/pub/5238'},
 {id:'e407a',name:'Processed eucheuma seaweed',codes:codes('e407a'),pattern:/\bprocessed eucheuma|\be\s*[-:]?\s*407\s*a\b/i,concern:'high',summary:'Semi-refined carrageenan. EFSA has been more cautious about specifications than for refined E407. Still authorised when specifications are met.',certainty:'Authorised with specifications',source:'https://www.efsa.europa.eu/en/efsajournal/pub/5238'},
 {id:'e432',name:'Polysorbate 20',codes:codes('e432','e433','e434','e435','e436'),pattern:/\bpolysorbate|\be\s*[-:]?\s*43[2-6]\b/i,concern:'high',summary:'Polysorbate emulsifiers. EFSA has re-evaluated this group and kept authorisations with numerical ADIs. Some experimental work on gut effects is why consumer apps flag them.',certainty:'Authorised emulsifiers; experimental findings are not a measured effect of this product',source:'https://www.efsa.europa.eu/en/efsajournal/pub/4112'},
 {id:'e466',name:'Sodium carboxymethyl cellulose',codes:codes('e466'),pattern:/\bcarboxymethyl cellulose|\bcarboxymethylcellulose|\bcmc\b|\be\s*[-:]?\s*466\b/i,concern:'moderate',summary:'Cellulose gum thickener. EFSA authorised it. Some studies of emulsifying fibres and the gut microbiome are why it appears in additive reviews.',certainty:'Authorised; gut-microbiome studies are not a product test',source:EFSA},
 {id:'e621',name:'Monosodium glutamate',codes:codes('e621','e620','e622','e623','e624','e625'),pattern:/\bmonosodium glutamate|\bglutamate|\bmsg\b|\be\s*[-:]?\s*62[0-5]\b/i,concern:'moderate',summary:'Flavour enhancer. EFSA set a group ADI for glutamates. Sensitive people report reactions; this is not an allergy test.',certainty:'Authorised flavour enhancer',source:'https://www.efsa.europa.eu/en/efsajournal/pub/4910'},
 {id:'e950',name:'Acesulfame K',codes:codes('e950'),pattern:/\bacesulfam(?:e|o)?(?:[ -]k)?\b|\be\s*[-:]?\s*950\b/i,concern:'moderate',summary:'EFSA reassessed acesulfame K in 2025 and set an ADI of 15 mg/kg body weight/day. WHO advises against relying on non-sugar sweeteners for long-term weight control. Presence is not an intake.',certainty:'Regulatory ADI plus conditional WHO guidance',source:'https://efsa.onlinelibrary.wiley.com/doi/10.2903/j.efsa.2025.9317'},
 {id:'e951',name:'Aspartame',codes:codes('e951'),pattern:/\baspartam(?:e|o)?\b|\be\s*[-:]?\s*951\b/i,concern:'high',summary:'IARC classified aspartame as possibly carcinogenic (Group 2B). JECFA/EFSA keep an ADI of 40 mg/kg/day for the general population, excluding people with PKU. Those are hazard vs risk assessments, not a dose from this pack.',certainty:'IARC hazard + EFSA ADI; PKU exclusion is medical',source:IARC_ASP},
 {id:'e952',name:'Cyclamate',codes:codes('e952'),pattern:/\bcyclamat|\be\s*[-:]?\s*952\b/i,concern:'high',summary:'Non-sugar sweetener, authorised in the EU with an ADI. Not authorised as a sweetener in the United States. WHO’s non-sugar sweetener guidance also applies.',certainty:'Jurisdiction-specific authorisation',source:WHO_NSS},
 {id:'e954',name:'Saccharin',codes:codes('e954'),pattern:/\bsaccharin|\be\s*[-:]?\s*954\b/i,concern:'moderate',summary:'Non-sugar sweetener. Older bladder-cancer concerns in rats were not confirmed as a human risk at authorised uses. WHO’s conditional guidance still advises against relying on non-sugar sweeteners for weight control.',certainty:'Authorised sweetener plus WHO population guidance',source:WHO_NSS},
 {id:'e955',name:'Sucralose',codes:codes('e955'),pattern:/\bsucralos(?:e|io)?\b|\be\s*[-:]?\s*955\b/i,concern:'moderate',summary:'EFSA’s 2026 review found no safety concern at currently authorised uses (ADI 15 mg/kg/day) but could not establish safety for a proposed bakery extension because of heating products.',certainty:'Current uses assessed; some heating conditions uncertain',source:'https://www.efsa.europa.eu/en/plain-language-summary/re-evaluation-sucralose-e-955-food-additive'},
 {id:'e960',name:'Steviol glycosides',codes:codes('e960','e960a','e960c'),pattern:/\bsteviol|\bstevia|\be\s*[-:]?\s*960[a-d]?\b/i,concern:'moderate',summary:'Plant-derived non-sugar sweetener. “Natural” is not a health rating. WHO’s conditional guidance advises against relying on non-sugar sweeteners for long-term weight control.',certainty:'Population guidance, not a toxicological ban',source:WHO_NSS},
 {id:'e300',name:'Ascorbic acid (vitamin C)',codes:codes('e300','e301','e302'),pattern:/\bascorbic|\bascorbate|\bvitamin c\b|\be\s*[-:]?\s*30[0-2]\b/i,concern:'low',summary:'Vitamin C used as an antioxidant. Authorised and nutritionally familiar. Combined with benzoates, benzene formation is a manufacturing control issue, not a reason to treat vitamin C as a risky additive on its own.',certainty:'Authorised nutrient/antioxidant',source:EFSA},
 {id:'e322',name:'Lecithins',codes:codes('e322'),pattern:/\blecithin|\blécithine|\be\s*[-:]?\s*322\b/i,concern:'low',summary:'Emulsifier from soya, sunflower or egg. EFSA considers lecithins of no safety concern at reported uses. Soya lecithin is relevant for soya allergy when declared.',certainty:'Authorised emulsifier; allergen depends on source',source:'https://www.efsa.europa.eu/en/efsajournal/pub/3147'},
 {id:'e330',name:'Citric acid',codes:codes('e330','e331','e332','e333'),pattern:/\bcitric acid|\bcitrate|\be\s*[-:]?\s*330\b|\be\s*[-:]?\s*331\b|\be\s*[-:]?\s*332\b|\be\s*[-:]?\s*333\b/i,concern:'low',summary:'Common acid and acidity regulator, including from fermentation. EFSA has no safety concern at reported uses.',certainty:'Authorised acid',source:EFSA},
 {id:'e270',name:'Lactic acid',codes:codes('e270','e325','e326','e327'),pattern:/\blactic acid|\blactate|\be\s*[-:]?\s*270\b|\be\s*[-:]?\s*32[5-7]\b/i,concern:'low',summary:'Fermentation acid used as a preservative and acidity regulator. Authorised without a numerical ADI as a normal metabolite.',certainty:'Authorised acid',source:EFSA},
 {id:'e296',name:'Malic acid',codes:codes('e296'),pattern:/\bmalic acid|\be\s*[-:]?\s*296\b/i,concern:'low',summary:'Fruit acid used as an acidity regulator. Authorised.',certainty:'Authorised acid',source:EFSA},
 {id:'e440',name:'Pectin',codes:codes('e440'),pattern:/\bpectin|\be\s*[-:]?\s*440\b/i,concern:'low',summary:'Fruit-fibre gelling agent. EFSA: no safety concern.',certainty:'Authorised fibre gelling agent',source:EFSA},
 {id:'e410',name:'Locust bean gum',codes:codes('e410'),pattern:/\blocust bean|\bcarob|\be\s*[-:]?\s*410\b/i,concern:'low',summary:'Seed-gum thickener. EFSA: no safety concern for the general population at reported uses.',certainty:'Authorised gum',source:EFSA},
 {id:'e412',name:'Guar gum',codes:codes('e412'),pattern:/\bguar gum|\be\s*[-:]?\s*412\b/i,concern:'low',summary:'Seed-gum thickener. Authorised. High supplemental doses can affect the gut; typical food use is lower.',certainty:'Authorised gum',source:EFSA},
 {id:'e414',name:'Acacia gum (gum arabic)',codes:codes('e414'),pattern:/\bgum arabic|\bacacia gum|\be\s*[-:]?\s*414\b/i,concern:'low',summary:'Tree-exudate gum. EFSA: no safety concern.',certainty:'Authorised gum',source:EFSA},
 {id:'e415',name:'Xanthan gum',codes:codes('e415'),pattern:/\bxanthan|\be\s*[-:]?\s*415\b/i,concern:'low',summary:'Fermentation gum thickener. EFSA: no safety concern at reported uses, with infant-food caveats that do not apply to general groceries.',certainty:'Authorised gum',source:EFSA},
 {id:'e471',name:'Mono- and diglycerides of fatty acids',codes:codes('e471'),pattern:/\bmono- and diglycerides|\bmono- et diglycérides|\be\s*[-:]?\s*471\b/i,concern:'low',summary:'Very common emulsifier. EFSA re-evaluated E471 and kept it authorised. Residual contaminants are controlled by specifications, not by this app.',certainty:'Authorised emulsifier',source:'https://www.efsa.europa.eu/en/efsajournal/pub/6885'},
 {id:'e500',name:'Sodium carbonates',codes:codes('e500','e501','e503'),pattern:/\bsodium carbonate|\bsodium bicarbonate|\bbicarbonate|\be\s*[-:]?\s*500\b|\be\s*[-:]?\s*501\b|\be\s*[-:]?\s*503\b/i,concern:'low',summary:'Raising agents and acidity regulators (baking soda family). Authorised.',certainty:'Authorised raising agent',source:EFSA},
 {id:'e160a',name:'Carotenes',codes:codes('e160a','e160b','e160c'),pattern:/\bcarotene|\bpaprika extract|\bannatto|\be\s*[-:]?\s*160\s*[abc]\b/i,concern:'low',summary:'Carotenoid colours, including beta-carotene and paprika extract. Authorised colours; some people are sensitive to annatto (E160b).',certainty:'Authorised colour',source:EFSA},
 {id:'e101',name:'Riboflavin',codes:codes('e101'),pattern:/\briboflavin|\bvitamin b2\b|\be\s*[-:]?\s*101\b/i,concern:'low',summary:'Vitamin B2 used as a yellow colour. Authorised nutrient.',certainty:'Authorised vitamin/colour',source:EFSA},
 {id:'e306',name:'Tocopherols',codes:codes('e306','e307'),pattern:/\btocopherol|\bvitamin e\b|\be\s*[-:]?\s*306\b|\be\s*[-:]?\s*307\b/i,concern:'low',summary:'Vitamin E antioxidants. Authorised.',certainty:'Authorised antioxidant',source:EFSA},
 {id:'e14xx',name:'Modified starch',codes:codes('e1404','e1410','e1412','e1413','e1414','e1420','e1422','e1440','e1442','e1450','e1451'),pattern:/\bmodified starch|\bamidon modifié|\be\s*[-:]?\s*14\d{2}\b/i,concern:'low',summary:'Starch treated for processing stability. EFSA considers modified starches of no safety concern at reported uses.',certainty:'Authorised carbohydrate additive',source:EFSA},
 {id:'e420',name:'Sorbitol',codes:codes('e420','e421','e953','e965','e966','e967','e968'),pattern:/\bsorbitol|\bmannitol|\bisomalt|\bmaltitol|\blactitol|\bxylitol|\berythritol|\be\s*[-:]?\s*420\b|\be\s*[-:]?\s*421\b|\be\s*[-:]?\s*953\b|\be\s*[-:]?\s*965\b|\be\s*[-:]?\s*966\b|\be\s*[-:]?\s*967\b|\be\s*[-:]?\s*968\b/i,concern:'low',summary:'Polyol sweeteners. Can have a laxative effect at higher intakes; packs often say so. WHO non-sugar-sweetener guidance does not cover polyols in the same way as aspartame-type sweeteners.',certainty:'Authorised; laxative effect is dose-dependent',source:EFSA},
];

export const additiveEvidenceReviewed='2026-09-14';

const byCode=new Map<string,AdditiveEvidence>();
for(const row of additiveEvidence)for(const code of row.codes)byCode.set(code.toLowerCase().replace(/[^a-z0-9]/g,''),row);

export function additiveCode(tag:string){
 return tag.toLowerCase().replace(/^[a-z]{2}:/,'').replace(/[^a-z0-9]/g,'');
}

export function lookupAdditive(tag:string){
 const code=additiveCode(tag);
 if(!code)return;
 return byCode.get(code)||(code.startsWith('e')?byCode.get(code.slice(0,4))||byCode.get(code.slice(0,5)):undefined);
}

export function matchAdditives(text:string,tags:string[]=[]){
 const found=new Map<string,AdditiveEvidence>();
 for(const tag of tags){
  const hit=lookupAdditive(tag);
  if(hit)found.set(hit.id,hit);
 }
 for(const row of additiveEvidence)if(row.pattern.test(text))found.set(row.id,row);
 const unknown=[...new Set(tags.map(additiveCode).filter(code=>/^e\d/.test(code)&&!lookupAdditive(code)))];
 return {known:[...found.values()],unknown};
}
