import {z} from 'zod';
import {dateSchema,nutritionSchema,safeLink,safePhoto} from './meal-schema';
const text=z.string().max(800),name=z.string().trim().min(1).max(160),strings=z.array(z.string().max(200)).max(100);
const amount=z.number().finite().positive().max(10000),price=z.number().finite().min(0).max(100000).nullable().optional();
const snapshot=z.object({id:z.string().min(1).max(120),name,brand:text.optional(),pack:text.optional(),barcode:z.string().max(14).optional(),image:z.string().max(600).optional(),ingredients:z.string().max(6000).optional(),categories:strings.default([]),countries:strings.default([]),allergens:strings.optional(),traces:strings.optional(),ingredientTags:strings.optional(),labels:strings.optional(),stores:strings.optional(),additives:strings.optional(),nutrition:nutritionSchema.optional(),basis:z.enum(['100g','100ml']).optional(),source:z.string().max(300).default('User-entered snapshot'),sourceUrl:z.string().max(600).optional(),retrieved:z.number().finite().default(0)}).passthrough();
const receipt=z.object({fingerprint:z.string().min(1).max(64),line:z.string().min(1).max(80),label:name,store:z.string().max(160),date:z.union([z.literal(''),dateSchema]),currency:z.enum(['EUR','USD','CHF','GBP','DKK','SEK','NOK','PLN','CZK','HUF','RON','ISK']),lineTotal:z.number().finite().min(0).max(100000).optional()});
const item=z.object({name,image:z.string().max(600).optional(),receipt:receipt.optional(),quantity:amount,unit:z.enum(['pack','piece','g','kg','ml','l']),pack:text.optional(),category:text.optional(),notes:text.optional(),product:snapshot.nullish(),assigned:z.string().max(120).optional(),intendedFor:z.string().max(120).optional(),store:text.optional(),priority:z.enum(['normal','high']).optional(),substitution:z.enum(['exact','brand','similar','ask']).optional(),price,actualPrice:price,done:z.boolean().optional(),order:z.number().finite().optional()}).passthrough();
export function validateRecord(kind:string,d:any,h:string){
 if(kind==='item'||kind==='favourite')d=item.parse(d);
 if(kind==='product')d=snapshot.parse(d);
 if(kind==='shop')d=z.object({name,address:z.string().trim().min(1).max(300),retailer:z.enum(['coop-ch','migros-ch','tesco-gb','carrefour-fr','walmart-us']),country:z.string().length(2),sourceUrl:z.string().max(600).optional(),placeId:z.string().max(160).optional(),evidence:z.enum(['map-listing','household-entered'])}).parse(d);
 if(kind==='list')d=z.object({name,store:text.optional(),archived:z.boolean().optional(),categoryOrder:strings.optional()}).passthrough().parse(d);
 if(kind==='template'||kind==='trip')d=z.object({name,items:z.array(item).max(200)}).passthrough().parse(d);
 if(kind==='observation')d=z.object({name,product:z.string().max(120).optional(),store:z.string().trim().min(1).max(160),date:dateSchema,price:z.union([z.literal(''),z.coerce.number().finite().min(0).max(100000)]).optional()}).passthrough().parse(d);
 if(kind==='feedback')d=z.object({product:z.string().min(1).max(120),feedback:z.enum(['Like','Dislike','Would buy again','Not a suitable substitute']),reason:z.string().max(500).optional()}).passthrough().parse(d);
 if(kind==='substitution')d=z.object({original:z.string().min(1).max(120),product:snapshot,country:z.string().length(2),reason:text}).passthrough().parse(d);
 function links(value:any):void{if(!value||typeof value!=='object')return;if(Array.isArray(value)){value.forEach(links);return}if(!safePhoto(value.image,h)||!safeLink(value.sourceUrl))throw Object.assign(new Error('Use an authorised household photo and an HTTPS source link.'),{status:400});for(const v of Object.values(value))if(v&&typeof v==='object')links(v)}links(d);return d;
}
export function anonymise(data:any,user:string):any{if(Array.isArray(data))return data.map(v=>anonymise(v,user));if(!data||typeof data!=='object')return data;return Object.fromEntries(Object.entries(data).filter(([k])=>k!=='personalNote'||(data.user!==user&&data.member!==user)).map(([k,v])=>[k,['user','member','addedBy','purchasedBy','reportedBy'].includes(k)&&v===user?'Deleted member':['assigned','intendedFor'].includes(k)&&v===user?'':anonymise(v,user)]))}
